"""empty message

Revision ID: adb993f143a1
Revises: 
Create Date: 2020-08-20 18:23:50.157840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb993f143a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AED_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lon', sa.String(length=15), nullable=False),
    sa.Column('lat', sa.String(length=15), nullable=False),
    sa.Column('add', sa.Text(), nullable=False),
    sa.Column('place', sa.Text(), nullable=False),
    sa.Column('mng', sa.String(length=30), nullable=False),
    sa.Column('mng_t', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sickness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sick', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sick_cha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sick_id', sa.Integer(), nullable=True),
    sa.Column('cha', sa.Text(), nullable=False),
    sa.Column('symp', sa.Text(), nullable=False),
    sa.Column('cop', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['sick_id'], ['sickness.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sick_cha')
    op.drop_table('sickness')
    op.drop_table('AED_info')
    # ### end Alembic commands ###
